# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.

# time COmplexity -> O(len(s) + len(t))

def findTheDifference(s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    # Credits -> https://leetcode.com/problems/find-the-difference/discuss/86881/Python-solution-which-beats-96
    # Use XOR operation
    result = 0
    for ch in s + t:
        result = result ^ ord(ch)
    return chr(result)

# Examples:
s = "abdc"
t = "xabcd"
print(findTheDifference(s, t))
